# SPDX-License-Identifier: Apache-2.0
"""Phase 5 community SDK — `sndr community new-patch` scaffold generator.

Drops a working draft plugin tree at
`plugins/community/<author>/<patch-id>/`. The generated tree validates
clean against `validate_manifest()` so the operator can immediately:

  1. Inspect the manifest YAML (commented per parameter).
  2. Implement the apply hook in patch.py (currently a no-op stub).
  3. Run `sndr community validate <id>` to confirm release-tier rules.
  4. Mark `publish_state: review` when ready for promotion.

The scaffolded manifest is ALWAYS `publish_state: draft` so it never
sneaks into the release registry by accident (§6.6 no-stub gate).
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Optional

from .manifest import DEFAULT_PLUGINS_DIR


__all__ = [
    "ScaffoldRequest",
    "scaffold_patch",
    "ScaffoldError",
]


_PATCH_ID_RE = re.compile(r"^[A-Z]{1,4}\d{1,4}[A-Z]?(?:_[A-Z0-9_]+)?$")
_AUTHOR_RE = re.compile(r"^[a-z][a-z0-9._-]*$")


class ScaffoldError(Exception):
    """Raised when the scaffold cannot proceed safely (e.g. target dir
    already populated, bad id format)."""


@dataclass
class ScaffoldRequest:
    patch_id: str                        # e.g. "PN999" or "P107_RETRY"
    author: str                          # e.g. "noonghunna" (lowercase kebab)
    family: str                          # e.g. "spec_decode" | "memory" | "tool_call"
    title: str
    type: str = "runtime_hook"           # values: "runtime_hook" | "text_patch" | "composite"
    license_str: str = "apache-2.0"
    root: Optional[Path] = None          # override plugins/community/ for tests


def _validate_request(req: ScaffoldRequest) -> None:
    if not _PATCH_ID_RE.match(req.patch_id):
        raise ScaffoldError(
            f"patch_id={req.patch_id!r} must match {_PATCH_ID_RE.pattern!r} "
            f"(e.g. 'PN999', 'P107', 'P12_RETRY')"
        )
    if not _AUTHOR_RE.match(req.author):
        raise ScaffoldError(
            f"author={req.author!r} must be lowercase alphanumeric "
            f"(plus . _ -); starts with a letter"
        )
    if req.type not in ("runtime_hook", "text_patch", "composite"):
        raise ScaffoldError(
            f"type={req.type!r} must be one of "
            f"`runtime_hook` / `text_patch` / `composite`"
        )


def _render_manifest_yaml(req: ScaffoldRequest) -> str:
    """Render the scaffold manifest YAML with per-parameter comments
    (matches W-B exemplar discipline used for V2 builtin configs)."""
    today = date.today().isoformat()
    env_flag = f"GENESIS_ENABLE_{req.patch_id}"
    return f"""# SPDX-License-Identifier: {req.license_str}
# Draft community patch — generated by `sndr community new-patch`.
# Marked `publish_state: draft` so it stays out of the release registry
# until the author flips it to `review` or `published`.

schema_version: 2                       # PROJECT_ROADMAP_V2 §4.5 schema
kind: patch
id: {req.patch_id}                        # canonical id; <Letter><Number>[_TAG]
namespace: community/{req.author}        # community/<author> | official | core

title: {req.title}
maintainer: {req.author}
version: 0.1.0                          # semver (Q6); bump on every release
license: {req.license_str}                  # SPDX identifier
created: '{today}'

# ─── Lifecycle + publish state (§6.6 boundary) ─────────────────────────
lifecycle: community-test                # community-test → community-validated → promoted → retired
implementation_status: experimental      # experimental | beta | stable | deprecated | disabled
publish_state: draft                     # draft → review → published → rejected
                                         # NEVER ship `draft` in release registry

# ─── Patch shape ──────────────────────────────────────────────────────
type: {req.type}                  # runtime_hook | text_patch | composite
family: {req.family}                    # spec_decode | memory | tool_call | ...
env_flag: {env_flag}
default_on: false                        # auto-enable; release blocks default_on if not published

# ─── Compatibility gates (research lesson 5) ──────────────────────────
compatibility:
  min_vllm_pin: null                     # earliest vllm pin where this patch is safe
  max_vllm_pin: null                     # null = no upper bound yet
  min_sndr_core_version: null            # min Genesis sndr_core
  max_sndr_core_version: null
  model_arch_required: []                # ['hybrid_gdn_moe'] etc. or [] for all
  cuda_capability_min: null              # null | [major, minor], e.g. [8, 6]

# ─── Target files (only for type: text_patch) ─────────────────────────
target_files: []                         # populate when type == text_patch:
                                         #   - path: vllm/engine/...
                                         #     target_module: vllm.engine.foo
                                         #     target_callable: bar
                                         #     context_md5: <md5 of pristine slice>
                                         #     pristine_fixture: ../../tests/fixtures/...

# ─── Cross-references ─────────────────────────────────────────────────
conflicts_with: []                       # ids that mutually exclude this patch
requires_patches: []                     # ids that must be enabled together

marker_attr: null                        # optional runtime self-check attribute name

# ─── Entry points (runtime_hook) ──────────────────────────────────────
entry_points:
  apply: plugins.community.{req.author}.{req.patch_id}.patch:apply
                                         # `module.path:callable_name`

# ─── Tests harness (validator R-5) ────────────────────────────────────
tests_required:
  - tests/test_{req.patch_id.lower()}.py   # at least one test glob must exist

# ─── Operator references ──────────────────────────────────────────────
references: []                           # URLs / issue links / paper refs
"""


def _render_patch_py(req: ScaffoldRequest) -> str:
    """Render a runnable patch.py stub that imports cleanly + provides
    an apply() callable (validator R-4 imports it on validate)."""
    return f'''# SPDX-License-Identifier: {req.license_str}
"""Community patch {req.patch_id} — entry-point implementation.

This is the scaffolded stub. Replace `apply()` body with the real patch
logic. The `apply()` callable signature is `apply(target, **kwargs) -> Any`
where `target` is the runtime object the patch wraps (engine, scheduler,
model worker — depends on `family`).

The stub returns None and emits a structured log line so an operator
can confirm the patch is being dispatched even before the real logic
lands.
"""
from __future__ import annotations

import logging

log = logging.getLogger("genesis.patch.{req.patch_id}")


def apply(target=None, **kwargs):  # noqa: D401 — entry-point hook
    """No-op stub. Replace with the actual patch logic.

    Returning None tells the dispatcher there is nothing to substitute.
    """
    log.info(
        "patch {req.patch_id} apply() called — stub no-op "
        "(replace with real implementation)"
    )
    return None
'''


def _render_init_py(req: ScaffoldRequest) -> str:
    return (
        f"# SPDX-License-Identifier: {req.license_str}\n"
        f'"""Community patch {req.patch_id} (namespace community/{req.author})."""\n'
    )


def _render_test_py(req: ScaffoldRequest) -> str:
    return f'''# SPDX-License-Identifier: {req.license_str}
"""Scaffolded test for community patch {req.patch_id}.

The validator's R-5 rule requires at least one test file per `tests_required`
glob. This is the minimal coverage — replace with real assertions when the
patch logic lands.
"""
from __future__ import annotations


def test_patch_module_imports():
    """The apply hook must import cleanly (mirrors validator R-4)."""
    from plugins.community.{req.author}.{req.patch_id} import patch
    assert callable(patch.apply)


def test_apply_returns_none_on_stub():
    """Default scaffold returns None. When you replace the body,
    update this assertion to match the real contract."""
    from plugins.community.{req.author}.{req.patch_id} import patch
    assert patch.apply(target=None) is None
'''


def scaffold_patch(req: ScaffoldRequest) -> Path:
    """Materialize the scaffold under `plugins/community/<author>/<id>/`.

    Returns the directory path. Refuses to overwrite an existing
    non-empty directory (the operator should explicitly rm first).
    """
    _validate_request(req)

    root = req.root if req.root is not None else DEFAULT_PLUGINS_DIR
    target = root / req.author / req.patch_id

    if target.exists() and any(target.iterdir()):
        raise ScaffoldError(
            f"target dir {target} already exists and is not empty — "
            f"remove it explicitly before re-scaffolding"
        )
    target.mkdir(parents=True, exist_ok=True)
    (target / "tests").mkdir(exist_ok=True)

    (target / "manifest.yaml").write_text(
        _render_manifest_yaml(req), encoding="utf-8",
    )
    (target / "__init__.py").write_text(
        _render_init_py(req), encoding="utf-8",
    )
    (target / "patch.py").write_text(
        _render_patch_py(req), encoding="utf-8",
    )
    (target / "tests" / "__init__.py").write_text("", encoding="utf-8")
    (target / "tests" / f"test_{req.patch_id.lower()}.py").write_text(
        _render_test_py(req), encoding="utf-8",
    )

    return target
