#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate Ed25519 trust anchor keypair offline — Wave 4.4.

Replaces the placeholder zero-key in `vllm/sndr_core/license.py`
with a real production key. The private key never enters the repo;
operator stores it offline (e.g., on an air-gapped machine, hardware
key, or 1Password).

Usage (Etap 0.2 hardened — private key никогда не уходит в stdout
по умолчанию, чтобы shell history / scrollback / screen recorders не
сохранили root-of-trust ключ):

  # Recommended: private key в файл (0600), public в stdout + license.py
  python3 scripts/generate_trust_anchor.py \\
      --out ~/.sndr/keys/trust_anchor --update-license

  # Manual workflow на air-gapped machine: явный opt-in для печати priv
  python3 scripts/generate_trust_anchor.py --print-private

  # Без --out и --print-private скрипт fail'ится с error: ключ нельзя
  # «сгенерировать в RAM и забыть» — оператор обязан явно указать,
  # куда уходит приватная половина.

Security notes:
  - Run on an air-gapped machine for production keys.
  - The private key MUST NOT be checked into git, copied to chat,
    or sent over plain network.
  - Store the private key in offline cold storage (paper, hardware
    token, air-gapped USB). After distribution of signed tokens
    finishes, the private key can stay offline indefinitely.
  - When rotating: keep the old key around long enough for in-flight
    customer tokens to be re-issued under the new key.

Output formats:
  Public key  → base64url (43 chars, no padding) — drop into
                `_TRUST_ANCHOR_PUBKEY_B64URL` in license.py.
  Private key → base64url (43 chars, no padding) — stored on disk
                with mode 0o600 if --out is specified.

Exit codes:
  0 — keypair generated successfully
  1 — cryptography library missing (`pip install cryptography`)
  2 — file write failed (e.g., target path already exists)
  3 — Etap 0.2: neither --out nor --print-private specified; refusing
       to generate a key that has nowhere to go
"""
from __future__ import annotations

import argparse
import base64
import os
import re
import stat
import sys
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent
LICENSE_PY = REPO_ROOT / "vllm" / "sndr_core" / "license.py"


def _b64url(raw: bytes) -> str:
    """Base64url-encode without padding (Ed25519 keys are 32 bytes
    → 43-char encoding)."""
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def generate_keypair() -> tuple[str, str]:
    """Generate a fresh Ed25519 keypair.

    Returns (pubkey_b64url, privkey_b64url).
    """
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PrivateKey,
        )
        from cryptography.hazmat.primitives import serialization
    except ImportError:
        print(
            "ERROR: cryptography library not installed. "
            "Run: pip install cryptography>=41.0",
            file=sys.stderr,
        )
        sys.exit(1)

    priv = Ed25519PrivateKey.generate()
    pub = priv.public_key()

    priv_bytes = priv.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_bytes = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return _b64url(pub_bytes), _b64url(priv_bytes)


def save_private_key(path: Path, privkey_b64: str) -> None:
    """Write private key to `path` with mode 0o600.

    Creates parent directory if missing. Refuses to overwrite an
    existing key file (operator must explicitly delete first).
    """
    if path.exists():
        print(
            f"ERROR: private key file already exists at {path}. "
            "Refusing to overwrite. Delete it first if you really "
            "want a new key (this BREAKS all existing tokens).",
            file=sys.stderr,
        )
        sys.exit(2)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(privkey_b64 + "\n", encoding="utf-8")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0o600


def update_license_py(pubkey_b64: str) -> bool:
    """In-place replace `_TRUST_ANCHOR_PUBKEY_B64URL` in license.py.

    Returns True on success.
    """
    if not LICENSE_PY.is_file():
        print(f"ERROR: {LICENSE_PY} not found", file=sys.stderr)
        return False
    text = LICENSE_PY.read_text(encoding="utf-8")
    # Match the assignment block (regex tolerant of multi-line value)
    pattern = re.compile(
        r"_TRUST_ANCHOR_PUBKEY_B64URL\s*=\s*\([^)]+\)",
        re.DOTALL,
    )
    new_block = (
        f'_TRUST_ANCHOR_PUBKEY_B64URL = (\n'
        f'    "{pubkey_b64}"  # generated by scripts/generate_trust_anchor.py\n'
        f")"
    )
    new_text, n = pattern.subn(new_block, text, count=1)
    if n == 0:
        print(
            "ERROR: could not find _TRUST_ANCHOR_PUBKEY_B64URL block in "
            f"{LICENSE_PY}. Did the file format change?",
            file=sys.stderr,
        )
        return False
    LICENSE_PY.write_text(new_text, encoding="utf-8")
    return True


def main(argv: Optional[list[str]] = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--out", type=Path, default=None,
        help="Save private key to this file path (mode 0o600). "
             "Recommended path для production: private key никогда не "
             "попадает в stdout/shell history.",
    )
    p.add_argument(
        "--print-private", action="store_true",
        help="Etap 0.2 (audit 2026-05-12): явный opt-in для печати "
             "private key в stdout. По умолчанию stdout содержит только "
             "public key — приватный либо в --out файл, либо требует "
             "этот флаг. Use only when copy-pasting на air-gapped machine "
             "и terminal scrollback под контролем.",
    )
    p.add_argument(
        "--update-license", action="store_true",
        help="Patch the new public key into vllm/sndr_core/license.py "
             "(replaces the placeholder zero-key).",
    )
    p.add_argument(
        "--quiet", action="store_true",
        help="Suppress security warnings + headers. Не меняет логику "
             "exposure private key — те же правила --out/--print-private.",
    )
    args = p.parse_args(argv)

    # Etap 0.2: operator должен явно решить, куда уходит private key.
    # Иначе ключ генерируется в RAM и теряется — это feature, не bug:
    # security-first default.
    if not args.out and not args.print_private:
        print(
            "ERROR: private key has nowhere to go.\n"
            "  Use --out PATH       (write to file, mode 0o600, RECOMMENDED)\n"
            "  OR --print-private   (print to stdout, careful with scrollback)\n"
            "Generating a key without retaining it is pointless — refusing.",
            file=sys.stderr,
        )
        return 3

    pub, priv = generate_keypair()

    if not args.quiet:
        print("=" * 78)
        print("Genesis trust anchor — Ed25519 keypair generated")
        print("=" * 78)
        print()

    # Public key — всегда в stdout (это безопасно копировать в license.py).
    print("PUBLIC  KEY (base64url, 32 bytes raw, drop into license.py):")
    print(f"  {pub}")
    print()

    # Private key — только при явном --print-private. Etap 0.2 fix:
    # раньше всегда печатался → shell history / scrollback / recorders
    # могли сохранить root-of-trust ключ.
    if args.print_private:
        print("PRIVATE KEY (base64url, 32 bytes raw, KEEP OFFLINE):")
        print(f"  {priv}")
        print()

    if args.out:
        save_private_key(args.out, priv)
        if not args.quiet:
            print(f"Private key written to: {args.out} (mode 0o600)")
            if not args.print_private:
                print(
                    "  (not printed in stdout — security-first default; "
                    "use --print-private to override)"
                )
            print()

    if args.update_license:
        if update_license_py(pub):
            if not args.quiet:
                print(f"Patched public key into: {LICENSE_PY}")
                print()
        else:
            return 2

    if not args.quiet:
        print("=" * 78)
        print("NEXT STEPS — security checklist:")
        print("=" * 78)
        print("  1. The private key is the SOLE root of trust for")
        print("     engine-tier license tokens. Without it, you cannot issue")
        print("     new tokens. Lose it = full key rotation required.")
        print("  2. NEVER commit the private key to git. Add the file path")
        print("     to .gitignore if you saved it via --out.")
        print("  3. Store the private key on offline storage:")
        print("       - Hardware key (YubiKey, etc.)")
        print("       - Air-gapped USB drive")
        print("       - Paper backup in a safe")
        print("       - 1Password / Bitwarden secure note")
        print("  4. To issue a customer token: read the private key into a")
        print("     signing tool, generate the token offline, distribute the")
        print("     signed token over secure channel.")
        print("  5. Rotate when:")
        print("       - Suspected compromise (e.g., key shown in stdout/logs)")
        print("       - Major version release (e.g., v12.0.0)")
        print("       - Annual policy review")
        print("=" * 78)
    return 0


if __name__ == "__main__":
    sys.exit(main())
