# SPDX-License-Identifier: Apache-2.0
"""Tests for ``scripts/audit_ai_attribution.py`` —
AUDIT-CLOSURE.1.A.6 (2026-05-26).

Coverage strategy:

  * Pure-function ``scan_text(text)`` exercised with crafted strings
    for every forbidden pattern + every allowlist class.
  * Inline allow marker covered (legitimate historical reference).
  * Live tracked-tree smoke confirms exit 0 after the CHANGELOG.md
    inline marker landed in the same commit.

The audit's purpose: automate the recurring ``grep -niwE
'claude|gpt|...'`` sweep run on every commit during 2026-05-26 Track F
closure. The forbidden set is narrow — attribution **syntax** only,
never bare AI tool names — so false positives near zero by construction.
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT_PATH = REPO_ROOT / "scripts" / "audit_ai_attribution.py"


def _import_audit_module():
    spec = importlib.util.spec_from_file_location(
        "audit_ai_attribution", SCRIPT_PATH
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules["audit_ai_attribution"] = mod
    spec.loader.exec_module(mod)
    return mod


@pytest.fixture
def audit_mod():
    return _import_audit_module()


class TestForbiddenPatterns:
    """Each documented forbidden pattern fires on a canonical example."""

    def test_co_authored_by_claude_flagged(self, audit_mod):
        text = "Some commit message body.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1
        lineno, label, snippet = findings[0]
        assert "Co-Authored-By" in label
        assert "Claude" in snippet

    def test_co_authored_by_chatgpt_flagged(self, audit_mod):
        text = "Co-Authored-By: ChatGPT\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1

    def test_co_authored_by_copilot_flagged(self, audit_mod):
        text = "Co-Authored-By: Copilot\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1

    def test_generated_by_chatgpt_flagged(self, audit_mod):
        text = "This module was Generated by ChatGPT for the operator.\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1
        assert "Generated-by" in findings[0][1]

    def test_generated_with_claude_code_promotional_flagged(self, audit_mod):
        text = "Some footer.\n\nGenerated with [Claude Code](https://...)\n"
        findings = audit_mod.scan_text(text)
        # The first pattern that matches wins; promotional footer expected.
        assert len(findings) == 1
        # Either Generated-by or Promotional label is acceptable — both
        # cover this construct; the audit reports whichever matches first.
        assert any(
            tag in findings[0][1]
            for tag in ("Generated-by", "Promotional", "footer")
        )

    def test_robot_emoji_generated_flagged(self, audit_mod):
        text = "Doc text\n\n🤖 Generated with [Claude Code]\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1

    def test_ai_assisted_prose_flagged(self, audit_mod):
        text = "This module is AI-assisted on the prose side.\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1
        assert "AI-assisted" in findings[0][1]

    def test_claude_assisted_suffix_flagged(self, audit_mod):
        text = "Section was Claude-assisted by the operator.\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1

    def test_powered_by_gpt_flagged(self, audit_mod):
        text = "Footer: Powered by GPT-4 for tier 3 inference.\n"
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1
        assert "Powered" in findings[0][1]


class TestLegitimateMentionsNotFlagged:
    """Bare AI-tool names in legitimate contexts must not fire."""

    def test_huggingface_model_id_with_claude_not_flagged(self, audit_mod):
        text = (
            "Reference: huggingface.co/raydelossantos/"
            "Qwen3.5-40B-Claude-4.6-Opus-Deckard-Heretic-GPTQ-Int4\n"
        )
        findings = audit_mod.scan_text(text)
        assert findings == [], f"unexpected findings: {findings}"

    def test_dot_claude_path_not_flagged(self, audit_mod):
        text = ".claude/settings.local.json\n"
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_claude_md_file_reference_not_flagged(self, audit_mod):
        text = "Previous pin dev338 retained per CLAUDE.md vLLM pin policy.\n"
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_gemini_code_assist_bot_credit_not_flagged(self, audit_mod):
        text = (
            "2 critical fixes from gemini-code-assist review on PR #40914 "
            "(shared u per request, denom==0 → 1.0)\n"
        )
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_anthropic_env_var_prefix_not_flagged(self, audit_mod):
        text = "envs: GENESIS|SNDR|VLLM|OPENAI|ANTHROPIC|HF|HUGGINGFACE\n"
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_claude_code_ide_client_in_bug_prose_not_flagged(self, audit_mod):
        text = (
            "agentic IDE clients (OpenClaw, Claude Code, Cline, Cursor) "
            "whose tool catalog included even one schema...\n"
        )
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_gemini_lowercase_in_gemma_word_not_flagged(self, audit_mod):
        """``gemma`` (the model family) does not match the forbidden
        ``Gemini Code Assist`` pattern thanks to word boundaries."""
        text = "prod-gemma4-31b-tq-default profile uses gemma4 tokenizer.\n"
        findings = audit_mod.scan_text(text)
        assert findings == []

    def test_sndr_compose_render_banner_not_flagged(self, audit_mod):
        """Tool-generated banner ``Generated by sndr compose render``
        must NOT match the ``Generated by ChatGPT`` pattern."""
        text = (
            "# Generated by `sndr compose render qwen3-6-27b...` — "
            "DO NOT edit by hand.\n"
        )
        findings = audit_mod.scan_text(text)
        assert findings == []


class TestInlineAllowMarker:
    """Inline operator-acknowledged override marker."""

    def test_marker_on_same_line_waives(self, audit_mod):
        # Fixture: single-line text with the violation + marker on the
        # same line. The trailing comment marker on THIS source line
        # also suppresses audit_ai_attribution's self-scan of this file.
        text = "- Removed the \"AI-assisted by author\" / \"Claude-assisted\" attribution <!-- audit-ai-attribution: allow -->\n"  # noqa: E501  <!-- audit-ai-attribution: allow -->
        findings = audit_mod.scan_text(text)
        assert findings == [], (
            f"inline allow marker should waive the line, got {findings}"
        )

    def test_marker_on_different_line_does_not_waive(self, audit_mod):
        """The marker must be on the SAME line as the violation; a
        marker on a different line does not waive."""
        # Build the multi-line fixture without putting Co-Authored-By
        # token verbatim in our own source — split the literal so the
        # self-audit doesn't trip on this file. Trailing source-line
        # markers belt-and-braces.
        co_auth = "Co-Authored" + "-By: Claude <bot@example.com>\n"  # noqa  <!-- audit-ai-attribution: allow -->
        text = "<!-- audit-ai-attribution: allow -->\n" + co_auth
        findings = audit_mod.scan_text(text)
        assert len(findings) == 1, (
            f"marker on prior line must not waive subsequent line, "
            f"got {findings}"
        )


class TestScopeFilter:
    """``_in_scope`` filter excludes binaries + private + retired."""

    def test_python_file_in_scope(self, audit_mod):
        # Use a different audit script — audit_ai_attribution.py itself
        # is on the self-exempt list (it carries the patterns it forbids).
        assert audit_mod._in_scope(
            "scripts/audit_links.py",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is True

    def test_audit_self_path_excluded(self, audit_mod):
        """Audit-tooling self-exemption — circular by design."""
        assert audit_mod._in_scope(
            "scripts/audit_ai_attribution.py",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is False
        assert audit_mod._in_scope(
            "tests/unit/scripts/test_audit_ai_attribution.py",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is False

    def test_markdown_file_in_scope(self, audit_mod):
        assert audit_mod._in_scope(
            "docs/CONTRIBUTING.md",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is True

    def test_png_excluded(self, audit_mod):
        assert audit_mod._in_scope(
            "assets/logo.png",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is False

    def test_sndr_private_excluded_by_default(self, audit_mod):
        assert audit_mod._in_scope(
            "sndr_private/planning/audits/some_doc.md",
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
        ) is False

    def test_sndr_private_included_with_flag(self, audit_mod):
        assert audit_mod._in_scope(
            "sndr_private/planning/audits/some_doc.md",
            audit_mod._EXCLUDED_SUBTREES_INCLUDE_PRIVATE,
        ) is True

    def test_retired_always_excluded(self, audit_mod):
        for excl in (
            audit_mod._EXCLUDED_SUBTREES_DEFAULT,
            audit_mod._EXCLUDED_SUBTREES_INCLUDE_PRIVATE,
        ):
            assert audit_mod._in_scope(
                "sndr/engines/vllm/patches/_retired/pn108.py",
                excl,
            ) is False


class TestLiveCorpus:
    """Live tracked-tree must be clean post-CHANGELOG-marker landing."""

    def _run(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, str(SCRIPT_PATH), *args],
            capture_output=True, text=True, cwd=REPO_ROOT, check=False,
        )

    def test_live_default_exit_zero(self):
        result = self._run()
        assert result.returncode == 0, (
            f"live tracked tree should be clean, got rc={result.returncode}\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
        assert "No forbidden AI-attribution markers" in result.stdout

    def test_live_json_shape(self):
        result = self._run("--json")
        assert result.returncode == 0
        data = json.loads(result.stdout)
        assert data["tracked_count"] == 0
        assert data["tracked_findings"] == []
        assert data["history_count"] == 0
        assert data["include_private"] is False
        assert data["strict_history"] is False

    def test_help_works(self):
        result = self._run("--help")
        assert result.returncode == 0
        assert "audit_ai_attribution" in result.stdout
        assert "--include-private" in result.stdout
        assert "--strict-history" in result.stdout

    def test_strict_history_does_not_change_exit_code(self):
        """``--strict-history`` is informational; even with history hits
        the exit code stays at the tracked-tree verdict (0 here)."""
        result = self._run("--strict-history")
        assert result.returncode == 0, (
            f"strict-history must not gate exit code, got rc={result.returncode}\n"
            f"stdout:\n{result.stdout}"
        )
