# SPDX-License-Identifier: Apache-2.0
"""Write-safe operator-local report bundle generation for the GUI.

Generates a redacted snapshot bundle from the read-only Product API and writes
it under the operator-local install dir (``$SNDR_HOME/reports/<id>/``). This is
the designated operator artifact location — it never writes into the repo, the
V2 catalog, or any remote/server host, and it runs no subprocess.

Redaction (default on) strips the operator's home directory and the GUI token
from the snapshot so a shared bundle does not leak local paths/secrets.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import asdict, dataclass, field, is_dataclass
from pathlib import Path
from typing import Any

REPORT_TYPES = ("catalog", "launch", "patch", "doctor")


@dataclass(frozen=True)
class ReportBundleResult:
    bundle_id: str
    report_type: str
    preset_id: str
    bundle_dir: str
    files: tuple[str, ...]
    redacted: bool
    created_at: float
    summary: str = ""
    note: str = field(default="Operator-local bundle; no repo/server write, no command executed.")


def _reports_dir() -> Path:
    from sndr.engines.vllm.locations.project_paths import install_root

    return install_root() / "reports"


def _payload(value: Any) -> Any:
    if is_dataclass(value) and not isinstance(value, type):
        return _payload(asdict(value))
    if isinstance(value, dict):
        return {key: _payload(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_payload(item) for item in value]
    return value


def _redact(value: Any, *, home: str, token: str | None) -> Any:
    if isinstance(value, str):
        out = value
        if home and home in out:
            out = out.replace(home, "~")
        if token and token in out:
            out = out.replace(token, "***")
        return out
    if isinstance(value, dict):
        return {key: _redact(item, home=home, token=token) for key, item in value.items()}
    if isinstance(value, list):
        return [_redact(item, home=home, token=token) for item in value]
    return value


def _collect_snapshot(report_type: str, preset_id: str) -> dict:
    """Assemble a read-only snapshot; each section degrades to an error note."""
    from .doctor import collect_doctor_report
    from .environment import collect_environment_report
    from .overview import collect_catalog_summary, collect_product_overview
    from .patches.doctor import run_doctor as run_patch_doctor

    sections: dict[str, Any] = {}

    def _safe(name: str, fn) -> None:
        try:
            sections[name] = _payload(fn())
        except Exception as exc:  # never fail the whole bundle on one section
            sections[name] = {"error": str(exc)}

    _safe("overview", collect_product_overview)
    _safe("catalog_summary", collect_catalog_summary)
    _safe("environment", collect_environment_report)

    if report_type in ("doctor", "launch", "catalog"):
        _safe("doctor", collect_doctor_report)
    if report_type in ("patch", "launch", "catalog"):
        _safe("patch_doctor", run_patch_doctor)
    if report_type == "launch" and preset_id:
        from .launch_plan import build_launch_plan

        _safe("launch_plan", lambda: build_launch_plan(preset_id=preset_id))
    if preset_id:
        from .presets import explain_preset

        _safe("preset_explain", lambda: explain_preset(preset_id))

    return sections


def _summary_md(report_type: str, preset_id: str, snapshot: dict) -> str:
    catalog = snapshot.get("catalog_summary", {}) or {}
    env = snapshot.get("environment", {}) or {}
    lines = [
        f"# SNDR {report_type} report",
        "",
        f"- report_type: {report_type}",
        f"- preset: {preset_id or '(none)'}",
        f"- engine: {env.get('engine_name', '-')} {env.get('engine_version', '') or '(not installed)'}",
        f"- sndr_core: {env.get('sndr_core_version', '-')}",
        f"- models: {catalog.get('models_count', '-')}",
        f"- presets: {catalog.get('presets_count', '-')}",
        "",
        "Read-only snapshot generated by the SNDR Control Center. "
        + "Redaction strips home paths and tokens by default.",
    ]
    return "\n".join(lines)


def generate_report_bundle(
    *,
    report_type: str = "catalog",
    preset_id: str = "",
    redact: bool = True,
) -> ReportBundleResult:
    """Generate a report bundle under ``$SNDR_HOME/reports/<id>/`` (write-safe)."""
    if report_type not in REPORT_TYPES:
        raise ValueError(
            f"Unknown report_type {report_type!r}; expected one of {REPORT_TYPES}"
        )

    created_at = time.time()
    snapshot = {
        "report_type": report_type,
        "preset_id": preset_id,
        "created_at": created_at,
        "sections": _collect_snapshot(report_type, preset_id),
    }

    if redact:
        token = os.environ.get("SNDR_GUI_TOKEN") or None
        snapshot = _redact(snapshot, home=str(Path.home()), token=token)

    seed = f"{report_type}:{preset_id}:{created_at}"
    bundle_id = "rpt_" + hashlib.sha256(seed.encode("utf-8")).hexdigest()[:10]
    bundle_dir = _reports_dir() / bundle_id
    bundle_dir.mkdir(parents=True, exist_ok=True)

    # default=str coerces non-JSON-native values (date/datetime, etc.) so a
    # single exotic field never fails the whole bundle.
    snapshot_text = json.dumps(snapshot, indent=2, sort_keys=True, default=str)
    (bundle_dir / "snapshot.json").write_text(snapshot_text, encoding="utf-8")
    summary = _summary_md(report_type, preset_id, snapshot["sections"])
    (bundle_dir / "summary.md").write_text(summary, encoding="utf-8")

    return ReportBundleResult(
        bundle_id=bundle_id,
        report_type=report_type,
        preset_id=preset_id,
        bundle_dir=str(bundle_dir),
        files=("snapshot.json", "summary.md"),
        redacted=redact,
        created_at=created_at,
        summary=summary,
    )
