// SPDX-License-Identifier: Apache-2.0
// Anchor source-of-truth status panel. Surfaces the per-pin anchor manifests
// (sndr/engines/vllm/pins/<pin>/anchors.json): each pin's vLLM/genesis version,
// file/patch/anchor counts, schema validity, which manifest is ACTIVE for the
// running engine, and live drift of the active manifest vs the installed source.
// Read-only; self-fetches /api/v1/patches/manifest.
import { Anchor, CircleAlert, CircleCheck, Loader2, RefreshCw } from "lucide-react";
import { tr } from "../i18n";
import { useApiQuery } from "../hooks/useApiQuery";
import { api, type AnchorManifestEntry } from "../api";
import { InfoRows } from "../components/primitives";

export function AnchorManifestPanel() {
  const { data, state, error, reload } = useApiQuery(
    ["patch-manifest"],
    (signal) => api.patchManifest(signal),
    { staleTime: 30_000 },
  );

  if (state === "loading" || state === "idle") {
    return <div className="muted"><Loader2 size={14} /> {tr("Loading anchor manifests…")}</div>;
  }
  if (state === "error") {
    return <div className="chat-advisory"><CircleAlert size={13} /> <span>{error ?? tr("Failed to load anchor manifests.")}</span></div>;
  }
  if (!data || !data.available) {
    return <div className="muted">{tr("No per-pin anchor manifests in this build (anchor source-of-truth not present).")}</div>;
  }

  const drift = data.drift;
  return (
    <div className="anchor-sot">
      <div className="anchor-sot-head">
        <span className="muted">{tr("Running vLLM")}: <strong>{data.running_vllm ?? tr("unknown")}</strong> · {data.manifest_count} {tr("manifest(s)")}</span>
        <button className="ghost-button" onClick={reload}><RefreshCw size={12} /> {tr("Refresh")}</button>
      </div>

      {data.manifests.length === 0
        ? <div className="muted">{tr("No per-pin manifests on disk.")}</div>
        : data.manifests.map((m) => <AnchorManifestCard key={m.pin_dir} m={m} />)}

      <div className="anchor-sot-drift">
        <h4><Anchor size={14} /> {tr("Live drift — active manifest vs installed source")}</h4>
        {!drift.checked
          ? <div className="muted">{tr("Not checked")}: {drift.reason ?? "-"}</div>
          : drift.in_sync
            ? <div className="anchor-ok"><CircleCheck size={14} /> {tr("In sync")} — {tr("every anchor matches the live source")} (0 {tr("drift")}).</div>
            : (
              <div className="anchor-bad">
                <div className="anchor-bad-head"><CircleAlert size={14} /> {drift.drift_count} {tr("anchor/file mismatch(es)")}{drift.truncated ? ` — ${tr("first")} ${drift.details?.length}` : ""}</div>
                <ul className="anchor-drift-list">
                  {(drift.details ?? []).map((d, i) => <li key={i}><code>{d}</code></li>)}
                </ul>
              </div>
            )}
      </div>
    </div>
  );
}

function AnchorManifestCard({ m }: { m: AnchorManifestEntry }) {
  if (m.error) {
    return <div className="anchor-card"><div className="anchor-card-head"><strong>{m.pin_dir}</strong> <span className="anchor-warn">{m.error}</span></div></div>;
  }
  return (
    <div className={`anchor-card${m.active ? " is-active" : ""}`}>
      <div className="anchor-card-head">
        <strong>{m.pin_dir}</strong>
        {m.active && <span className="anchor-badge active">{tr("active")}</span>}
        <span className={`anchor-badge ${m.schema_valid ? "ok" : "bad"}`}>{m.schema_valid ? tr("schema valid") : `${m.schema_errors.length} ${tr("schema errors")}`}</span>
      </div>
      <InfoRows rows={[
        [tr("vLLM pin"), m.vllm ?? "-"],
        [tr("Genesis"), m.genesis ?? "-"],
        [tr("Files / Patches / Anchors"), `${m.files} / ${m.patches} / ${m.anchors}`],
        [tr("Generated"), m.generated_at ?? "-"],
        [tr("Generated by"), m.generated_by ?? "-"],
      ]} />
    </div>
  );
}
