# SPDX-License-Identifier: Apache-2.0
"""S3.2 (UNIFIED_CONFIG plan 2026-05-09; audit P3-2 closure 2026-05-12):
`sndr quadlet render` — Podman Quadlet (.container) renderer.

Зачем
-----
Podman Quadlet — рекомендованный путь для production-grade systemd-
managed containers без root daemon (как Docker compose). Operator
кладёт `<name>.container` файл в `~/.config/containers/systemd/`,
делает `systemctl --user daemon-reload`, и systemd сам запускает
контейнер. Genesis не имел этого пути — operator'у приходилось
вручную переводить bash launch-script в Quadlet формат.

Формат
------
Quadlet — это INI-подобный формат с секциями `[Unit]`, `[Container]`,
`[Service]`, `[Install]`. Podman читает его и генерирует под капотом
полноценный `.service` файл.

Минимальный пример:

    [Unit]
    Description=Genesis vLLM (preset X)
    After=network.target

    [Container]
    Image=vllm/vllm-openai:nightly
    ContainerName=vllm-genesis
    PublishPort=8000:8000
    Volume=/srv/models:/models:ro
    Environment=GENESIS_ENABLE_X=1
    Exec=vllm serve /models/...

    [Service]
    Restart=on-failure

    [Install]
    WantedBy=default.target

Test contract — `tests/unit/cli/test_quadlet_render.py`:
  • Все обязательные секции присутствуют.
  • Environment lines рендерят все env vars (по одной на строку).
  • Volume lines рендерят все mounts с host_paths substitution.
  • PublishPort правильный.
  • Exec строка — vllm serve <args>.
  • Идемпотентность.
"""
from __future__ import annotations

import argparse
import shlex
from pathlib import Path
from typing import Any, Optional

from . import _io
from .compose import _container_command, _load_host_paths, _resolve_mount, _resolve


__all__ = [
    "add_argparser", "render_quadlet",
    "run_quadlet_render",
]


def add_argparser(subparsers: Any) -> None:
    p = subparsers.add_parser(
        "quadlet",
        help="Podman Quadlet (.container) renderer (audit P3-2).",
        description=(
            "Рендерит preset как Podman Quadlet `<name>.container` файл "
            "для systemd-managed запуска через `systemctl --user`. "
            "Альтернатива docker compose для rootless production "
            "deployment'ов."
        ),
    )
    sub = p.add_subparsers(dest="quadlet_cmd", required=True)

    p_render = sub.add_parser(
        "render", help="Render preset → <name>.container на stdout/файл",
    )
    p_render.add_argument("config", help="preset key")
    p_render.add_argument(
        "-o", "--output", default=None,
        help=(
            "Записать в файл (рекомендовано: "
            "~/.config/containers/systemd/<name>.container)."
        ),
    )
    p_render.set_defaults(func=run_quadlet_render)


def render_quadlet(cfg, host_paths: Optional[dict[str, str]] = None) -> str:
    """Рендерит ModelConfig в Podman Quadlet формат."""
    if host_paths is None:
        host_paths = _load_host_paths()

    docker = cfg.docker
    if docker is None:
        raise ValueError(
            f"preset {cfg.key!r} has no docker block — quadlet "
            "requires a container image / name / port."
        )

    container_name = docker.container_name or f"sndr-{cfg.key}"
    image = docker.effective_image_ref()
    host_port = docker.effective_host_port()
    container_port = docker.effective_container_port()

    # Environment lines — одна на строку. Quadlet принимает Environment=
    # повторяющиеся записи.
    env_pairs: list[tuple[str, str]] = []
    for k, v in cfg.system_env.items():
        env_pairs.append((str(k), str(v)))
    for k, v in cfg.genesis_env.items():
        env_pairs.append((str(k), str(v)))
    if cfg.api_key and not any(k == "VLLM_API_KEY" for k, _ in env_pairs):
        env_pairs.append(("VLLM_API_KEY", str(cfg.api_key)))

    # Volume lines с host_paths substitution.
    volumes: list[str] = [
        _resolve_mount(m, host_paths)
        for m in (docker.mounts or [])
    ]

    # Exec= одна строка. Podman не интерпретирует `\` continuation —
    # должна быть однострочная команда. Shlex-quote отдельных аргументов
    # на случай spaces.
    exec_argv = _container_command(cfg)
    exec_line = " ".join(shlex.quote(a) for a in exec_argv)

    lines: list[str] = []
    lines.append(
        "# Generated by `sndr quadlet render` — DO NOT edit by hand."
    )
    lines.append(f"# Source preset: {cfg.key} ({cfg.title})")
    lines.append(f"# Maintainer: {cfg.maintainer}")
    lines.append("#")
    lines.append(
        "# Install: place this file at "
        "~/.config/containers/systemd/<name>.container"
    )
    lines.append(
        "# Reload: systemctl --user daemon-reload && "
        f"systemctl --user start {container_name}.service"
    )
    lines.append("")
    lines.append("[Unit]")
    lines.append(f"Description=Genesis vLLM (preset {cfg.key})")
    lines.append("After=network-online.target")
    lines.append("Wants=network-online.target")
    lines.append("")
    lines.append("[Container]")
    lines.append(f"Image={image}")
    lines.append(f"ContainerName={container_name}")
    lines.append(f"PublishPort={host_port}:{container_port}")
    if docker.shm_size:
        lines.append(f"ShmSize={docker.shm_size}")
    # GPU access — Podman Quadlet supports AddDevice= for nvidia.
    lines.append("AddDevice=nvidia.com/gpu=all")
    if docker.network:
        lines.append(f"Network={docker.network}")
    for vol in volumes:
        lines.append(f"Volume={vol}")
    for k, v in env_pairs:
        lines.append(f"Environment={k}={v}")
    lines.append(f"Exec={exec_line}")
    lines.append("")
    lines.append("[Service]")
    lines.append("Restart=on-failure")
    lines.append("TimeoutStartSec=900")
    lines.append("")
    lines.append("[Install]")
    lines.append("WantedBy=default.target")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def run_quadlet_render(args: argparse.Namespace) -> int:
    cfg = _resolve(args.config)
    if cfg is None:
        return 2
    out = render_quadlet(cfg)
    if args.output:
        Path(args.output).write_text(out)
        _io.info(f"wrote {args.output} ({len(out)} bytes)")
    else:
        print(out)
    return 0
