#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Phase 3 relocation invariant audit.

Enforces the four architectural rules from
``sndr_private/planning/audits/RELOCATION_DESIGN_2026-05-21_RU.md`` §0.5:

  R1 — ``integrations/gemma4/`` is a small compatibility namespace.
       Only patches whose technical area of influence is genuinely
       Gemma-4-specific may live here. Everything else must live
       under its technical-area owner (kv_cache/, spec_decode/,
       attention/turboquant/, etc.).

  R2 — Canonical apply path is one. Registry ``apply_module`` must
       point at the NEW location (post-relocation), not at the
       compatibility shim. Shims at the old paths are redirects
       only — they exist for one release window and never become
       canonical.

  R3 — TQ / config boundary. Every ``GENESIS_*`` / ``SNDR_*`` env
       emitted by ``compose()`` / declared in a V2 profile must be
       registered in the canonical config-keys catalog (so
       ``sndr config-keys-describe`` resolves and operator-facing
       introspection is complete).

  R4 — No launcher / deploy scripts under ``integrations/``. The
       integrations tree is for patch code only. Host launchers,
       docker-run wrappers, deploy templates and operational
       scripts live under ``sndr_private/scripts/launch/``, are
       generated by ``sndr profile render-launchers``, or live in
       a dedicated public ``deploy/`` tree.

The script is idempotent and read-only — it never modifies files,
registry, or git state.

Exit codes:

  0 — all selected rules pass (clean tree).
  1 — at least one violation found.
  2 — audit tooling itself failed (import error, missing dependency).

Usage:

  python3 scripts/audit_phase3_relocation.py --rule all
  python3 scripts/audit_phase3_relocation.py --rule R1 --verbose
  python3 scripts/audit_phase3_relocation.py --json > /tmp/audit.json
"""
from __future__ import annotations

import argparse
import io
import json
import re
import sys
import tokenize
from pathlib import Path

# Repo layout — resolved relative to this script's location.
REPO_ROOT = Path(__file__).resolve().parent.parent

# Ensure the repo's vllm/ is importable as a top-level package when the
# audit runs from a clean shell (no install, no PYTHONPATH set).
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
INTEGRATIONS = REPO_ROOT / "vllm" / "sndr_core" / "integrations"
GEMMA4_DIR = INTEGRATIONS / "gemma4"
REGISTRY_FILE = REPO_ROOT / "vllm" / "sndr_core" / "dispatcher" / "registry.py"
STRUCTURED_PROFILE = (
    REPO_ROOT / "vllm" / "sndr_core" / "model_configs" / "builtin"
    / "profile" / "gemma4-tq-mtp-structured-k4.yaml"
)


# ─── R1: Gemma whitelist ────────────────────────────────────────────────

# Post-Phase-2.5 (2026-05-22): integrations/gemma4/ is forbidden.
# Every previous occupant has been relocated to its technical-area
# canonical home:
#   * 18 real G4 patches + _gemma4_detect + __init__ → model_compat/gemma4/  (Phase 2.2)
#   * 4 Gemma-only Triton kernels + kernels/__init__  → model_compat/gemma4/kernels/ (Phase 2.3)
#   * 11-file PR42637 overlay subtree                 → attention/turboquant/overlays/pr42637/ (Phase 2.4)
#   * 41 Phase-3 shims + 10 kernel shims              → deleted (Phase 2.1)
# R1 now asserts the directory does NOT exist, instead of allowlisting
# what is permitted inside.

# Shim sentinel — the marker we put in the docstring of every
# compatibility shim left at an old path during a relocation.
SHIM_SENTINEL = "Compatibility shim"


def _is_shim(path: Path) -> bool:
    """A file is a shim if its docstring contains SHIM_SENTINEL near the top."""
    try:
        head = path.read_text()[:400]
    except OSError:
        return False
    return SHIM_SENTINEL in head


def _shim_target(path: Path) -> str | None:
    """Extract the canonical target path that a shim redirects to.

    Pattern: ``from vllm.sndr_core.integrations.<family>.<module> import *``.
    Returns the dotted module path, or None if no redirect found.
    """
    try:
        text = path.read_text()
    except OSError:
        return None
    m = re.search(
        r"from (vllm\.sndr_core\.integrations\.[\w.]+) import \*",
        text,
    )
    return m.group(1) if m else None


def check_r1_gemma_whitelist() -> list[str]:
    """R1: integrations/gemma4/ directory MUST NOT exist (Phase 2.5).

    Phase 2.2..2.4 of the production cleanup workstream relocated
    every tracked file out of integrations/gemma4/ to its
    technical-area canonical home. Phase 2.5 (2026-05-22) deletes
    the now-empty directory and flips this audit from "allowlist
    permitted contents" to "the directory itself is forbidden".

    Any reintroduction of the path (intentional or accidental — e.g.,
    a future relocation revert, a fresh G4 patch landed in the wrong
    family bucket, or a stray .DS_Store creating an inode) flips
    this audit red so the regression is caught at the canonical
    Genesis gate, not at boot.
    """
    if GEMMA4_DIR.exists():
        return [
            f"R1: integrations/gemma4/ exists at {GEMMA4_DIR} — "
            f"this path is forbidden post-Phase-2.5. Every G4 patch / "
            f"kernel / overlay belongs to a technical-area family "
            f"(model_compat/gemma4/, attention/turboquant/overlays/, etc.). "
            f"If you need to add something Gemma-specific, route it to "
            f"the appropriate technical-area bucket; do not recreate "
            f"this directory."
        ]
    return []


# ─── R2: Canonical apply path ───────────────────────────────────────────


def _load_registry() -> dict[str, dict[str, object]]:
    """Import PATCH_REGISTRY without triggering torch / vllm imports."""
    from vllm.sndr_core.dispatcher.registry import PATCH_REGISTRY  # noqa: WPS433
    return PATCH_REGISTRY


def check_r2_canonical_apply_path() -> list[str]:
    """R2: registry apply_module never points at a shim file."""
    issues: list[str] = []
    try:
        registry = _load_registry()
    except Exception as e:  # noqa: BLE001
        return [f"R2: cannot import PATCH_REGISTRY: {type(e).__name__}: {e}"]

    for pid, meta in registry.items():
        apply_module = meta.get("apply_module")
        if not apply_module:
            continue
        # Convert dotted module to repo path.
        rel_parts = apply_module.split(".")
        # Expect: vllm.sndr_core.integrations.<family-or-deeper>.<module>
        if rel_parts[:3] != ["vllm", "sndr_core", "integrations"]:
            continue
        file_path = REPO_ROOT.joinpath(*rel_parts).with_suffix(".py")
        if not file_path.exists():
            # Other audits (apply_module coverage in audit_registry_contract)
            # already report missing files; not our concern.
            continue
        if _is_shim(file_path):
            issues.append(
                f"R2: {pid} apply_module={apply_module!r} resolves to a "
                f"shim file at {file_path.relative_to(REPO_ROOT)}. "
                f"Registry must point at the NEW canonical location, "
                f"not the old shim path."
            )
    return issues


# ─── R3: TQ / config boundary ───────────────────────────────────────────

# Envs declared in the validated structured profile that are read by
# integration modules at runtime but were not yet in the canonical
# config-keys catalog when Phase 3 closed. These are tracked here as
# documented pending registration so the audit does not block other
# Phase 3 work. Adding each to PATCH_REGISTRY closes the entry.
#
# History:
#   Phase 3 Bucket 6 (2026-05-21) introduced this set with 6 entries
#   sourced from the V2 config completeness audit §4.2.
#   R3 cleanup (2026-05-21, same day) closed all 6 by adding registry
#   entries: G4_70, G4_70B, PN256, PN261, PN271, PN274. The waiver
#   set is now empty.
#
# Add a new entry here only when a future profile change introduces an
# env whose patch hasn't been registered yet AND the registration
# work is being explicitly deferred to a follow-up commit. The
# entry must reference a tracking issue / audit doc.
PENDING_REGISTRATION: frozenset[str] = frozenset()


def _registered_env_flags() -> set[str]:
    """Set of env_flag values registered in PATCH_REGISTRY."""
    try:
        registry = _load_registry()
    except Exception:  # noqa: BLE001
        return set()
    flags: set[str] = set()
    for meta in registry.values():
        flag = meta.get("env_flag")
        if isinstance(flag, str):
            flags.add(flag)
    return flags


def _structured_profile_envs() -> list[str]:
    """Parse the gemma4-tq-mtp-structured-k4 profile for GENESIS_/SNDR_ envs."""
    if not STRUCTURED_PROFILE.is_file():
        return []
    text = STRUCTURED_PROFILE.read_text()
    # Match `    GENESIS_ENABLE_X: '1'` and `    SNDR_X: '1'` lines.
    return re.findall(r"^\s+((?:GENESIS_|SNDR_)\w+)\s*:", text, flags=re.M)


def check_r3_config_boundary() -> tuple[list[str], list[str]]:
    """R3: structured-profile envs are registered (or pending).

    Returns ``(errors, infos)``. PENDING_REGISTRATION envs are
    surfaced as ``infos`` (not errors) — they are known gaps that
    a future commit closes by adding a PATCH_REGISTRY entry. Envs
    that are neither registered nor in PENDING_REGISTRATION are
    surfaced as errors.
    """
    errors: list[str] = []
    infos: list[str] = []

    if not STRUCTURED_PROFILE.is_file():
        return [f"R3: structured profile missing: {STRUCTURED_PROFILE}"], []

    profile_envs = _structured_profile_envs()
    if not profile_envs:
        return [f"R3: no envs parsed from {STRUCTURED_PROFILE.name}"], []

    registered = _registered_env_flags()
    for env in sorted(set(profile_envs)):
        if env in registered:
            continue
        if env in PENDING_REGISTRATION:
            infos.append(
                f"R3: {env} declared by structured profile but not yet "
                f"in PATCH_REGISTRY (pending registration — see "
                f"PENDING_REGISTRATION in audit_phase3_relocation.py)."
            )
            continue
        errors.append(
            f"R3: {env} is declared by the structured profile but is "
            f"NOT in PATCH_REGISTRY and NOT in PENDING_REGISTRATION. "
            f"Either add a registry entry (preferred) or add to "
            f"PENDING_REGISTRATION with a tracking issue."
        )
    return errors, infos


# ─── R4: No launcher / deploy scripts under integrations/ ───────────────


_SHELL_EXTS = {".sh", ".bash", ".zsh"}

# Subprocess / os entry points that, if called with a "docker"/"vllm"
# first argument, would constitute a real launcher invocation inside
# patch code. Detecting these requires AST-level analysis; the
# heuristic below catches the common patterns without false-positives
# on documentation strings (such as the P103 text-patch payload that
# carries shell snippets as concatenated string literals).
_LAUNCHER_CALL_PATTERNS = (
    re.compile(r"\b(?:subprocess|sp)\.(?:run|Popen|check_call|check_output|call)\s*\(\s*\[?\s*['\"](?:docker|vllm)\b"),
    re.compile(r"\bos\.(?:system|popen|execv?p?|execvpe?)\s*\(\s*['\"](?:docker|vllm)\b"),
)


def check_r4_no_launchers_under_integrations() -> list[str]:
    """R4: no shell scripts / launcher subprocess invocations under integrations/.

    Two sub-checks:

    (a) Hard ban — any ``.sh`` / ``.bash`` / ``.zsh`` file under
        ``integrations/`` is a violation. Launchers live in
        ``sndr_private/scripts/launch/`` or in a public ``deploy/``
        tree, never alongside patch code. This was the original
        Phase 3 audit finding (3 violators in
        ``spec_decode/gateway/deploy/server/`` closed by Bucket 5).

    (b) Soft ban — Python files under ``integrations/`` must not
        contain executable ``subprocess.*`` / ``os.system`` /
        ``os.exec*`` calls whose first string argument starts with
        ``docker`` or ``vllm``. That would be a launcher
        invocation hiding inside patch code.

    String literals that merely *mention* shell commands (e.g. P103's
    text-patch payload that carries chunk.py modifications, or a
    docstring explaining how a launcher script is structured) are
    NOT violations — they are data, not executable launcher logic.
    The regex deliberately anchors on a call-site pattern so it
    cannot match arbitrary documentation strings.
    """
    issues: list[str] = []
    if not INTEGRATIONS.is_dir():
        return [f"R4: integrations/ directory missing: {INTEGRATIONS}"]

    # (a) Shell-script files.
    for path in INTEGRATIONS.rglob("*"):
        if path.is_file() and path.suffix in _SHELL_EXTS:
            issues.append(
                f"R4: {path.relative_to(REPO_ROOT)} — shell-script "
                f"under integrations/. Relocate to "
                f"sndr_private/scripts/launch/ or a public deploy/ tree."
            )

    # (b) Real launcher subprocess invocations in code.
    for path in INTEGRATIONS.rglob("*.py"):
        if path.parent.name == "__pycache__":
            continue
        try:
            text = path.read_text()
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            for pattern in _LAUNCHER_CALL_PATTERNS:
                if pattern.search(line):
                    issues.append(
                        f"R4: {path.relative_to(REPO_ROOT)}:{lineno} — "
                        f"launcher subprocess invocation in patch code: "
                        f"{line.strip()!r}. Move launcher logic to "
                        f"cli/profile.py render-launchers or a private "
                        f"scripts/ location."
                    )
                    break
    return issues


# ─── CLI driver ─────────────────────────────────────────────────────────


RULES = {
    "R1": ("Gemma whitelist", check_r1_gemma_whitelist),
    "R2": ("canonical apply path", check_r2_canonical_apply_path),
    "R3": ("TQ/config boundary", None),  # handled specially (errors + infos)
    "R4": ("no launchers under integrations/", check_r4_no_launchers_under_integrations),
}


def _run_rule(rule: str) -> tuple[list[str], list[str]]:
    """Return (errors, infos) for one rule."""
    if rule == "R3":
        return check_r3_config_boundary()
    _, fn = RULES[rule]
    return fn(), []  # type: ignore[misc]


def _emit_text(
    results: dict[str, tuple[list[str], list[str]]],
    verbose: bool,
) -> None:
    """Write a human-readable report to stdout."""
    print()
    print("╭──────────────────────────────────────────────────────────╮")
    print("│  Phase 3 relocation audit                                │")
    print("╰──────────────────────────────────────────────────────────╯")
    print()
    for rule, (errors, infos) in results.items():
        title = RULES[rule][0]
        if errors:
            print(f"  ✗ {rule}  {title}: {len(errors)} violation(s)")
            for issue in errors:
                print(f"      {issue}")
        else:
            print(f"  ✓ {rule}  {title}: clean")
        if verbose and infos:
            print(f"      ── informational ({len(infos)}) ──")
            for info in infos:
                print(f"      ℹ {info}")
    total_err = sum(len(e) for e, _ in results.values())
    total_info = sum(len(i) for _, i in results.values())
    print()
    if total_err:
        print(f"  ✗ {total_err} violation(s) — exit 1")
    else:
        suffix = f" + {total_info} informational" if total_info else ""
        print(f"  ✓ All selected rules clean{suffix} — exit 0")
    print()


def _emit_json(results: dict[str, tuple[list[str], list[str]]]) -> None:
    payload = {
        rule: {
            "title": RULES[rule][0],
            "violations": errors,
            "infos": infos,
            "status": "fail" if errors else "pass",
        }
        for rule, (errors, infos) in results.items()
    }
    payload["_summary"] = {
        "violations_total": sum(len(e) for e, _ in results.values()),
        "infos_total": sum(len(i) for _, i in results.values()),
    }
    json.dump(payload, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
    )
    parser.add_argument(
        "--rule",
        choices=("all", *RULES.keys()),
        default="all",
        help="which rule to check (default: all).",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit machine-readable JSON instead of human-readable report.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="include informational (non-failing) findings in text output.",
    )
    args = parser.parse_args(argv)

    rules = list(RULES.keys()) if args.rule == "all" else [args.rule]

    try:
        results = {rule: _run_rule(rule) for rule in rules}
    except Exception as e:  # noqa: BLE001
        sys.stderr.write(
            f"audit_phase3_relocation: tooling error: "
            f"{type(e).__name__}: {e}\n"
        )
        return 2

    if args.json:
        _emit_json(results)
    else:
        _emit_text(results, verbose=args.verbose)

    total_errors = sum(len(errors) for errors, _ in results.values())
    return 1 if total_errors else 0


if __name__ == "__main__":
    sys.exit(main())
