#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""audit_ai_attribution.py — attribution-label policy audit
(§9.A.6, AUDIT-CLOSURE.1.A.6, 2026-05-26).

Forbids syntactic AI-attribution constructs in tracked-tree source files
+ commit-style trailers + promotional footers. Permits legitimate
mentions of AI tool names that appear inside:

  * GitHub bot reviewer credits (``gemini-code-assist``, ``gemini-bot``)
  * HuggingFace model identifiers containing AI labels
    (``Qwen3.5-40B-Claude-4.6-Opus-...``)
  * Filesystem-path references (``.claude/``, ``CLAUDE.md``)
  * Env-var prefixes (``ANTHROPIC_API_KEY``, ``OPENAI_API_BASE``)
  * IDE client product names ("Claude Code" / "Cline" / "Cursor" in
    bug-context prose)
  * Inline operator-acknowledged exceptions via
    ``<!-- audit-ai-attribution: allow -->`` on the offending line

Detection strategy: narrow forbidden-pattern set targeting attribution
**syntax** (Co-Authored-By trailer, "Generated with/by <AI>",
``🤖 Generated``, "AI-assisted", etc.). Bare mentions of AI tool names
are NEVER flagged — the recurring class we automate is the explicit
attribution trailer that slips into commit messages and code comments.

This audit closes the recurring manual ``grep -niwE 'claude|gpt|...'``
sweep operator-and-Claude-Code ran on every commit during the
2026-05-26 Track F closure session (~11 commits, ~5 min each).
Permanent automation replaces ad-hoc grep.

Exit codes:
  0 — no forbidden attribution markers in scope
  1 — at least one forbidden marker found (file:line:pattern surfaced)
  2 — internal error (git not available, scope unloadable)

Modes:

  python3 scripts/audit_ai_attribution.py            # human-readable
  python3 scripts/audit_ai_attribution.py --json     # machine-readable
  python3 scripts/audit_ai_attribution.py --include-private  # also scan sndr_private/
  python3 scripts/audit_ai_attribution.py --strict-history   # ALSO scan git log
                                                              # (report-only,
                                                              # never blocks)
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent


# ─── Forbidden attribution patterns ───────────────────────────────────────
#
# Match syntactic attribution constructs, never bare AI-tool names.
# Each entry is (compiled regex, human-readable label).

_FORBIDDEN_PATTERNS: tuple[tuple[re.Pattern, str], ...] = (
    # Commit trailers — Co-Authored-By with AI agent name (not a person name).
    (
        re.compile(
            r"Co-[Aa]uthored-[Bb]y:\s+"
            r"(?:Claude|GPT-?\d?|ChatGPT|Copilot|Gemini|Anthropic|OpenAI|AI)\b"
        ),
        "Co-Authored-By trailer with AI agent name",
    ),
    # Generated-by attribution (NOT "Generated by sndr compose" tool banners).
    (
        re.compile(
            r"\bGenerated\s+(?:by|with)\s+"
            r"(?:Claude|ChatGPT|GPT-?[34]|Copilot|"
            r"Gemini\s+Code\s+Assist|Anthropic|OpenAI)\b"
        ),
        "Generated-by AI agent",
    ),
    # Promotional footer pattern (e.g. "Generated with [Claude Code]").
    (
        re.compile(
            r"Generated\s+with\s+\[(?:Claude|ChatGPT|GPT|Copilot)"
        ),
        "Promotional 'Generated with [AI]' footer",
    ),
    # Robot emoji + Generated (the canonical Anthropic / similar marker).
    (
        re.compile(r"🤖\s+Generated"),
        "Robot-emoji Generated marker",
    ),
    # AI-assisted / AI-generated prose.
    (
        re.compile(r"\bAI-?(?:assisted|generated|authored)\b"),
        "AI-assisted/generated prose",
    ),
    # Tool-specific suffix attribution.
    (
        re.compile(
            r"\b(?:Claude|GPT|ChatGPT|Copilot|Gemini)-assisted\b"
        ),
        "<AI>-assisted suffix attribution",
    ),
    # Promotional "Powered by".
    (
        re.compile(
            r"\bPowered\s+by\s+"
            r"(?:Claude|ChatGPT|GPT-?\d?|Anthropic|OpenAI)\b",
            re.IGNORECASE,
        ),
        "Promotional 'Powered by AI' attribution",
    ),
)


# Inline-override marker. The line carrying this marker (anywhere on the
# line) is exempt from this audit. Operator opt-in for legitimate
# historical references; matches the convention used by
# ``audit_public_docs`` (which uses ``<!-- audit-public-docs: allow -->``).
INLINE_ALLOW_MARKER = "<!-- audit-ai-attribution: allow -->"


# ─── Tracked-tree scope ───────────────────────────────────────────────────


# Text file extensions worth scanning. Binary types skipped.
_SCANNED_EXTENSIONS: frozenset[str] = frozenset({
    ".py", ".md", ".yaml", ".yml", ".json", ".toml", ".jinja",
    ".sh", ".txt", ".cfg", ".ini",
})


# Subtree exclusions. ``sndr_private/`` is operator-private and reviewed
# separately; ``_retired/`` and ``_archive/`` are historical and not
# subject to current-policy enforcement.
_EXCLUDED_SUBTREES_DEFAULT: tuple[str, ...] = (
    "sndr_private/",
    "sndr/engines/vllm/patches/_retired/",
    "tests/legacy/",
)
_EXCLUDED_SUBTREES_INCLUDE_PRIVATE: tuple[str, ...] = (
    "sndr/engines/vllm/patches/_retired/",
    "tests/legacy/",
)


# Audit-tooling self-exemption. The audit script's docstring + regex
# literals + label strings contain the patterns it forbids by
# necessity (they describe what to detect). Its test file contains
# the same patterns as test fixtures. Scanning these files would be
# circular — the audit can't detect attribution by describing
# attribution syntax without containing examples of it. Operators
# inspecting the audit's correctness read these files directly.
_SELF_EXEMPT_PATHS: frozenset[str] = frozenset({
    "scripts/audit_ai_attribution.py",
    "tests/unit/scripts/test_audit_ai_attribution.py",
})


@dataclasses.dataclass
class Finding:
    path: str
    line: int
    pattern_label: str
    snippet: str

    def as_dict(self) -> dict:
        return dataclasses.asdict(self)


def _git_ls_files() -> list[str]:
    """Return tracked-tree files via ``git ls-files``."""
    result = subprocess.run(
        ["git", "ls-files"],
        capture_output=True, text=True, cwd=REPO_ROOT, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"git ls-files failed (rc={result.returncode}): {result.stderr}"
        )
    return [line for line in result.stdout.splitlines() if line]


def _in_scope(path: str, excluded_subtrees: tuple[str, ...]) -> bool:
    """Return True if ``path`` should be scanned."""
    if path in _SELF_EXEMPT_PATHS:
        return False
    if any(path.startswith(prefix) for prefix in excluded_subtrees):
        return False
    suffix = Path(path).suffix.lower()
    return suffix in _SCANNED_EXTENSIONS


def scan_text(text: str) -> list[tuple[int, str, str]]:
    """Return list of (line_number_1based, pattern_label, line_text) for
    every forbidden match in ``text``. Honors inline allow marker."""
    out: list[tuple[int, str, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        if INLINE_ALLOW_MARKER in line:
            continue
        for pat, label in _FORBIDDEN_PATTERNS:
            if pat.search(line):
                out.append((lineno, label, line.strip()))
                break  # one finding per line is enough
    return out


def audit_tracked_tree(
    *,
    include_private: bool = False,
    root: Optional[Path] = None,
) -> list[Finding]:
    """Scan tracked tree under ``root`` (default: REPO_ROOT) and return
    every forbidden attribution match.

    Exits with ``RuntimeError`` if ``git ls-files`` cannot be invoked
    (e.g. running outside a git checkout).
    """
    root = root or REPO_ROOT
    excluded = (
        _EXCLUDED_SUBTREES_INCLUDE_PRIVATE
        if include_private
        else _EXCLUDED_SUBTREES_DEFAULT
    )

    files = _git_ls_files()
    findings: list[Finding] = []
    for rel in files:
        if not _in_scope(rel, excluded):
            continue
        full = root / rel
        try:
            text = full.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue  # skip binaries / unreadable
        for lineno, label, snippet in scan_text(text):
            findings.append(Finding(
                path=rel,
                line=lineno,
                pattern_label=label,
                snippet=snippet,
            ))
    return findings


def audit_git_history(*, max_count: int = 500) -> list[Finding]:
    """Scan the last ``max_count`` commit messages for the same forbidden
    patterns (report-only; never gates).

    Returns findings keyed by commit SHA in ``path`` field with
    ``line=0`` and the matched commit-message line in ``snippet``.
    """
    result = subprocess.run(
        ["git", "log", f"-n{max_count}",
         "--pretty=format:--SHA--%H%n%B%n--END--"],
        capture_output=True, text=True, cwd=REPO_ROOT, check=False,
    )
    if result.returncode != 0:
        return []

    findings: list[Finding] = []
    current_sha = None
    for line in result.stdout.splitlines():
        if line.startswith("--SHA--"):
            current_sha = line[len("--SHA--"):].strip()
            continue
        if line.startswith("--END--"):
            current_sha = None
            continue
        if current_sha is None:
            continue
        if INLINE_ALLOW_MARKER in line:
            continue
        for pat, label in _FORBIDDEN_PATTERNS:
            if pat.search(line):
                findings.append(Finding(
                    path=f"git:{current_sha[:12]}",
                    line=0,
                    pattern_label=label,
                    snippet=line.strip(),
                ))
                break
    return findings


def _render_text(findings: list[Finding], history_findings: list[Finding]) -> str:
    lines: list[str] = []
    lines.append("audit-ai-attribution: attribution-label policy")
    lines.append("─" * 70)
    lines.append(f"  tracked-tree findings: {len(findings)}")
    for f in findings[:50]:
        lines.append(f"    ✗ {f.path}:{f.line}  [{f.pattern_label}]")
        lines.append(f"        {f.snippet[:120]}{'…' if len(f.snippet) > 120 else ''}")
    if len(findings) > 50:
        lines.append(f"    … ({len(findings) - 50} more)")
    lines.append("")
    if history_findings:
        lines.append(
            f"  --strict-history findings: {len(history_findings)} "
            f"(report-only; never gates)"
        )
        for f in history_findings[:20]:
            lines.append(f"    · {f.path}  [{f.pattern_label}]")
            lines.append(f"        {f.snippet[:120]}{'…' if len(f.snippet) > 120 else ''}")
        if len(history_findings) > 20:
            lines.append(f"    … ({len(history_findings) - 20} more)")
        lines.append("")
    if findings:
        lines.append(
            "  ✗ Forbidden AI-attribution markers detected. Either:\n"
            "      1. Remove the attribution (preferred), OR\n"
            "      2. Add the inline marker to acknowledge the line is\n"
            f"         legitimate: {INLINE_ALLOW_MARKER}"
        )
    else:
        lines.append("  ✓ No forbidden AI-attribution markers")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--json", action="store_true",
                    help="emit machine-readable JSON")
    ap.add_argument("--include-private", action="store_true",
                    help="also scan sndr_private/ tree (default: skip)")
    ap.add_argument("--strict-history", action="store_true",
                    help="also scan last 500 commit messages (report-only)")
    args = ap.parse_args()

    try:
        findings = audit_tracked_tree(include_private=args.include_private)
    except RuntimeError as e:
        print(f"audit-ai-attribution: {e}", file=sys.stderr)
        return 2

    history_findings: list[Finding] = []
    if args.strict_history:
        history_findings = audit_git_history()

    if args.json:
        print(json.dumps({
            "tracked_findings": [f.as_dict() for f in findings],
            "history_findings": [f.as_dict() for f in history_findings],
            "tracked_count": len(findings),
            "history_count": len(history_findings),
            "include_private": args.include_private,
            "strict_history": args.strict_history,
        }, indent=2, sort_keys=True))
    else:
        print(_render_text(findings, history_findings))

    # History findings never gate. Tracked-tree findings gate at exit 1.
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
