#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""audit_generated_links.py — link integrity for AUTO-generated docs
(§9.A.4, AUDIT-CLOSURE.2, 2026-05-27).

Sibling to ``audit_links.py`` (which gates path/anchor integrity across
every markdown file). This audit narrows to **generator output** and
catches the failure modes specific to mechanically-rendered link tables:

  * Generator out-of-sync vs source-of-truth (``--check`` regression).
  * Number ↔ URL mismatch in ``[#NNNN](URL)`` shapes (e.g.,
    ``[#41127](https://github.com/vllm-project/vllm/pull/40000)`` — link
    text says 41127 but URL points at 40000; the generator should
    enforce these in lock-step).
  * Malformed GitHub PR URL (must match
    ``https://github.com/<org>/<repo>/(pull|issues)/<num>``).
  * Empty / placeholder URLs (``external://...`` is a Genesis-internal
    convention for "evidence URL pending"; the audit notes them but
    accepts the marker; bare ``TODO`` / ``...`` / ``None`` strings fail).

Generated docs in scope:

  - ``docs/PATCHES_AUTO.md``    (generated from ``dispatcher/registry.py``)
  - ``docs/CONFIGS_AUTO.md``    (generated from ``model_configs/builtin/*.yaml``)

Each is regenerated by its companion script; this audit calls each
generator's ``--check`` mode then runs the per-doc link-shape rules.

Exit codes
──────────

  0 — every generated doc in sync; every link shape passes
  1 — generator out-of-sync OR malformed link
  2 — internal error / generator script missing

Modes
─────

  python3 scripts/audit_generated_links.py            # human-readable
  python3 scripts/audit_generated_links.py --json     # machine-readable
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent


# ─── Generator manifest ───────────────────────────────────────────────────


@dataclasses.dataclass
class GeneratedDoc:
    rel_path: str           # repo-relative path to the generated .md
    generator: str          # repo-relative path to the generator script
    check_flag: str = "--check"


_GENERATED_DOCS: tuple[GeneratedDoc, ...] = (
    GeneratedDoc(
        rel_path="docs/PATCHES_AUTO.md",
        generator="scripts/generate_patches_md.py",
    ),
    GeneratedDoc(
        rel_path="docs/CONFIGS_AUTO.md",
        generator="scripts/generate_configs_md.py",
    ),
)


# ─── Link-shape patterns ──────────────────────────────────────────────────


# `[#NNNN](https://...)` — verify URL ends with `/NNNN`.
_NUMBERED_PR_LINK = re.compile(
    r"\[#(?P<num>\d+)\]\((?P<url>https?://[^)\s]+)\)"
)

# `[#<anything-but-digits>](https://...)` — catches the C.5 bug class
# where the generator put a URL (or other non-numeric token) into the
# link-text slot. Example shape we caught:
# ``[#https://github.com/...issues/39407](https://github.com/.../pull/https://...)``
# Number-prefixed text is the only legitimate shape; any non-digit
# text after the ``#`` is a generator bug.
_MALFORMED_HASH_LINK = re.compile(
    r"\[#(?P<text>[^\]\n]*?)\]\((?P<url>https?://[^)\s]+)\)"
)

# GitHub PR/issue URL shape.
_GH_PR_URL = re.compile(
    r"^https?://github\.com/[\w.-]+/[\w.-]+/(?:pull|issues)/\d+/?$"
)

# Placeholder / TODO / dangling.
_PLACEHOLDER_TARGETS: frozenset[str] = frozenset({
    "TODO", "todo", "...", "None", "null", "pending", "TBD",
})


# ─── Finding ──────────────────────────────────────────────────────────────


@dataclasses.dataclass
class Finding:
    doc: str
    line: int
    rule: str
    detail: str

    def as_dict(self) -> dict:
        return dataclasses.asdict(self)


# ─── Generator freshness ──────────────────────────────────────────────────


def _check_generator(doc: GeneratedDoc) -> Optional[str]:
    """Return error message if generator is out-of-sync, else None."""
    script = REPO_ROOT / doc.generator
    if not script.is_file():
        return f"generator script missing: {doc.generator}"
    result = subprocess.run(
        [sys.executable, str(script), doc.check_flag],
        capture_output=True, text=True, cwd=REPO_ROOT, check=False,
    )
    if result.returncode != 0:
        return (
            f"{doc.generator} --check returned rc={result.returncode}; "
            f"regenerate via `python3 {doc.generator}`. "
            f"stderr: {result.stderr.strip()[:200]}"
        )
    return None


# ─── Per-doc link-shape rules ─────────────────────────────────────────────


def _scan_numbered_pr_links(
    doc: GeneratedDoc, text: str,
) -> list[Finding]:
    findings: list[Finding] = []
    for m in _NUMBERED_PR_LINK.finditer(text):
        lineno = text.count("\n", 0, m.start()) + 1
        num = m.group("num")
        url = m.group("url").rstrip("/")
        # Number must match URL's trailing segment.
        if not url.endswith("/" + num):
            findings.append(Finding(
                doc=doc.rel_path,
                line=lineno,
                rule="R-GENLINK-1",
                detail=(
                    f"link text [#{num}] does not match URL trailing "
                    f"segment: {m.group('url')}"
                ),
            ))
            continue
        # URL must be GitHub PR/issue shape.
        if not _GH_PR_URL.match(m.group("url")):
            findings.append(Finding(
                doc=doc.rel_path,
                line=lineno,
                rule="R-GENLINK-2",
                detail=(
                    f"URL not in GitHub PR/issue shape "
                    f"(<org>/<repo>/(pull|issues)/<num>): "
                    f"{m.group('url')}"
                ),
            ))
    return findings


def _scan_malformed_hash_links(
    doc: GeneratedDoc, text: str,
) -> list[Finding]:
    """Detect ``[#<non-numeric>](URL)`` shapes — generator put a URL
    or other token into the link-text slot where only ``\\d+`` belongs.

    Caught the C.5 bug class on docs/PATCHES_AUTO.md where 28 rows
    rendered as ``[#https://github.com/...issues/N](https://.../pull/https://...)``
    because ``generate_patches_md.py`` only dispatched ``int``/``None``
    branches and let ``str`` URLs fall through the f-string template.
    """
    findings: list[Finding] = []
    for m in _MALFORMED_HASH_LINK.finditer(text):
        link_text = m.group("text")
        # Allow purely-numeric text (the legitimate shape) — the
        # _scan_numbered_pr_links rule already handles those.
        if link_text.isdigit():
            continue
        lineno = text.count("\n", 0, m.start()) + 1
        findings.append(Finding(
            doc=doc.rel_path,
            line=lineno,
            rule="R-GENLINK-4",
            detail=(
                f"malformed link-text [#{link_text[:60]}…] — only "
                f"numeric tokens are legitimate after the `#` "
                f"(URL: {m.group('url')[:60]}…)"
                if len(link_text) > 60 or len(m.group('url')) > 60
                else f"malformed link-text [#{link_text}] — only "
                f"numeric tokens are legitimate after the `#` "
                f"(URL: {m.group('url')})"
            ),
        ))
    return findings


def _scan_placeholder_targets(
    doc: GeneratedDoc, text: str,
) -> list[Finding]:
    """Detect `[text](TODO)` / `[text](pending)` / similar shells where
    the URL slot carries a stand-in token instead of a real target."""
    findings: list[Finding] = []
    pat = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    for m in pat.finditer(text):
        target = m.group(1).strip()
        if target in _PLACEHOLDER_TARGETS:
            lineno = text.count("\n", 0, m.start()) + 1
            findings.append(Finding(
                doc=doc.rel_path,
                line=lineno,
                rule="R-GENLINK-3",
                detail=(
                    f"placeholder URL token {target!r} — generator "
                    f"left a TODO marker in the link target"
                ),
            ))
    return findings


# ─── Audit ────────────────────────────────────────────────────────────────


def audit_generated_docs(
    *, docs: tuple[GeneratedDoc, ...] = _GENERATED_DOCS,
) -> list[Finding]:
    findings: list[Finding] = []
    for doc in docs:
        doc_path = REPO_ROOT / doc.rel_path
        if not doc_path.is_file():
            findings.append(Finding(
                doc=doc.rel_path,
                line=0,
                rule="R-GENLINK-0",
                detail="generated doc missing — generator was never run",
            ))
            continue
        # 1. Generator freshness.
        err = _check_generator(doc)
        if err is not None:
            findings.append(Finding(
                doc=doc.rel_path,
                line=0,
                rule="R-GENLINK-FRESHNESS",
                detail=err,
            ))
            # Don't bail — still run link-shape rules on the stale file.
        text = doc_path.read_text(encoding="utf-8", errors="replace")
        # 2. Numbered PR link consistency.
        findings.extend(_scan_numbered_pr_links(doc, text))
        # 3. Malformed link-text after `#` (catches the C.5 bug class).
        findings.extend(_scan_malformed_hash_links(doc, text))
        # 4. Placeholder targets.
        findings.extend(_scan_placeholder_targets(doc, text))
    return findings


# ─── Render ───────────────────────────────────────────────────────────────


def _render_text(findings: list[Finding]) -> str:
    lines: list[str] = []
    lines.append("audit-generated-links: link integrity for AUTO-generated docs")
    lines.append("─" * 70)
    lines.append(f"  generated docs scanned: {len(_GENERATED_DOCS)}")
    lines.append(f"  findings:               {len(findings)}")
    by_rule: dict[str, int] = {}
    for f in findings:
        by_rule[f.rule] = by_rule.get(f.rule, 0) + 1
    for rule, count in sorted(by_rule.items()):
        lines.append(f"    {rule:24s} {count}")
    lines.append("")
    for f in findings[:50]:
        lines.append(f"  ✗ {f.doc}:{f.line}  [{f.rule}]")
        lines.append(f"      {f.detail}")
    if len(findings) > 50:
        lines.append(f"  … ({len(findings) - 50} more)")
    if not findings:
        lines.append("  ✓ All generated docs in sync; all link shapes pass")
    else:
        lines.append("")
        lines.append(
            "  ✗ Fix: regenerate the auto doc (`python3 <generator>.py`) "
            "AND/OR fix the source registry/YAML the generator reads from."
        )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--json", action="store_true",
                    help="emit machine-readable JSON")
    args = ap.parse_args()

    try:
        findings = audit_generated_docs()
    except Exception as e:
        print(f"audit-generated-links: {type(e).__name__}: {e}",
              file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps({
            "findings": [f.as_dict() for f in findings],
            "count": len(findings),
            "docs_scanned": [d.rel_path for d in _GENERATED_DOCS],
        }, indent=2, sort_keys=True))
    else:
        print(_render_text(findings))

    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
