#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Auto-discover `apply_module` values for PATCH_REGISTRY entries.

Entry 12 of ROADMAP_EVIDENCE_LEDGER flagged 126/136 patches missing
`apply_module` metadata in `dispatcher.PATCH_REGISTRY` (the V2 register).
They WORK at runtime (legacy `@register_patch` decorator path), but the
V2 metadata is incomplete, so the §6.8 patch-proof gate (rule P-2) marks
them as needing operator follow-up.

This script proposes apply_module values by introspecting the legacy
register (`vllm.sndr_core.apply._state.PATCH_REGISTRY` — a list of
`(name, wrapped_fn)` tuples) and matching the name's leading patch id
back to the dispatcher dict. The real apply function lives at
`wrapped_fn.__wrapped__.__module__` (the decorator preserves the
original via functools.wraps).

Modes:

  python3 scripts/discover_apply_modules.py                # report (default)
  python3 scripts/discover_apply_modules.py --json         # machine-readable
  python3 scripts/discover_apply_modules.py --coverage     # numeric summary
  python3 scripts/discover_apply_modules.py --emit-py FILE # write Python
                                                           # snippet that an
                                                           # operator can paste
                                                           # into the registry

Exit code:
  0 — proposals computed (regardless of how many)
  2 — registry helpers unavailable / internal error
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


# Leading patch-id pattern, matches: P58, P67b, P15B, PN94, PN94B, P107.
_PID_RE = re.compile(r"^(P[A-Z]?N?\d+[a-zA-Z]?)\b")


@dataclass(frozen=True)
class Proposal:
    """One proposed mapping from patch_id → apply_module."""
    patch_id: str
    legacy_name: str
    proposed_apply_module: str
    current_apply_module: str | None
    needs_update: bool


def _real_module_for_legacy_fn(fn) -> str | None:
    """Unwrap the `@register_patch` decorator to find the real function's
    containing module. Returns None when the function has no __wrapped__
    attribute (manual register, not decorator-wrapped)."""
    wrapped = getattr(fn, "__wrapped__", None)
    if wrapped is None:
        return None
    return getattr(wrapped, "__module__", None)


def _extract_patch_id(name: str) -> str | None:
    """Pull the leading P-code from a legacy register name."""
    m = _PID_RE.match(name)
    return m.group(1) if m else None


def build_proposals() -> list[Proposal]:
    """Walk legacy + dispatcher registries and return proposed
    `apply_module` values for every entry that:
      • can be name-mapped from the legacy register
      • currently has no `apply_module` declared, OR has a value that
        disagrees with the auto-discovered one
    """
    try:
        from sndr.apply._state import PATCH_REGISTRY as LEG
        from sndr.dispatcher.registry import PATCH_REGISTRY
    except ImportError as e:
        raise SystemExit(f"could not import registries: {e}")

    # Build name → real-module map from the legacy register.
    legacy_map: dict[str, str] = {}
    for name, fn in LEG:
        pid = _extract_patch_id(name)
        if not pid:
            continue
        mod = _real_module_for_legacy_fn(fn)
        if not mod:
            continue
        # Earlier entry wins on collision (legacy register is ordered).
        legacy_map.setdefault(pid, mod)

    proposals: list[Proposal] = []
    for patch_id, meta in PATCH_REGISTRY.items():
        proposed = legacy_map.get(patch_id)
        if not proposed:
            continue        # No legacy entry → no proposal possible.
        current = meta.get("apply_module")
        needs_update = (current != proposed)
        proposals.append(Proposal(
            patch_id=patch_id,
            legacy_name=patch_id,
            proposed_apply_module=proposed,
            current_apply_module=current,
            needs_update=needs_update,
        ))
    return proposals


def _emit_py_snippet(proposals: list[Proposal]) -> str:
    """Render a copy-paste-friendly Python snippet that an operator
    could paste into a one-off migration script that updates
    `dispatcher/registry.py` in place via AST/text edits. We deliberately
    DON'T attempt that edit ourselves — `registry.py` is 2000+ lines of
    literal dict; safer for the operator to review the proposed mapping
    in this snippet and apply it via their preferred tooling.
    """
    lines = [
        "# AUTO-GENERATED by scripts/discover_apply_modules.py",
        "# Proposed apply_module mapping for PATCH_REGISTRY entries.",
        "# Review each line before applying — auto-discovery uses the",
        "# legacy `@register_patch` decorator's wrapped function module.",
        "",
        "PROPOSED_APPLY_MODULES = {",
    ]
    for p in proposals:
        if not p.needs_update:
            continue
        # current value is shown as a comment trail for safety.
        comment = (
            f"  # current={p.current_apply_module!r}"
            if p.current_apply_module is not None
            else "  # no current value"
        )
        lines.append(
            f'    {p.patch_id!r}: {p.proposed_apply_module!r},{comment}'
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--coverage", action="store_true",
                    help="Numeric summary only (no per-patch listing).")
    ap.add_argument("--emit-py", metavar="FILE", default=None,
                    help="Write a copy-pasteable Python snippet to FILE.")
    args = ap.parse_args()

    proposals = build_proposals()
    needing_update = [p for p in proposals if p.needs_update]
    already_set = [p for p in proposals
                   if not p.needs_update and p.current_apply_module]

    # Compute coverage: how many of dispatcher PATCH_REGISTRY entries
    # would have apply_module set IF we applied every proposal.
    from sndr.dispatcher.registry import PATCH_REGISTRY
    total = len(PATCH_REGISTRY)
    with_proposal = len(proposals)
    coverage_before = sum(
        1 for v in PATCH_REGISTRY.values() if v.get("apply_module")
    )
    coverage_after = coverage_before + len(needing_update)

    summary = {
        "total_patches": total,
        "patches_with_legacy_match": with_proposal,
        "patches_already_set": len(already_set),
        "patches_needing_update": len(needing_update),
        "patches_without_legacy_match": total - with_proposal,
        "coverage_before_pct": round(coverage_before / total * 100, 1) if total else 0,
        "coverage_after_pct": round(coverage_after / total * 100, 1) if total else 0,
    }

    if args.emit_py:
        Path(args.emit_py).write_text(_emit_py_snippet(proposals),
                                      encoding="utf-8")

    if args.json:
        print(json.dumps({
            "summary": summary,
            "proposals": [
                {
                    "patch_id": p.patch_id,
                    "proposed_apply_module": p.proposed_apply_module,
                    "current_apply_module": p.current_apply_module,
                    "needs_update": p.needs_update,
                }
                for p in proposals
            ],
        }, indent=2, sort_keys=True))
        return 0

    print(f"discover_apply_modules: {total} patches in dispatcher.PATCH_REGISTRY")
    print("─" * 70)
    print(f"  patches with legacy register match:  {with_proposal}")
    print(f"  patches WITHOUT legacy match:        {total - with_proposal}")
    print(f"  apply_module already set:            {len(already_set)}")
    print(f"  apply_module needs update:           {len(needing_update)}")
    print()
    print("  Coverage if all proposals applied:")
    print(f"    before:  {coverage_before}/{total}  "
          f"({summary['coverage_before_pct']}%)")
    print(f"    after:   {coverage_after}/{total}  "
          f"({summary['coverage_after_pct']}%)")
    print()

    if args.coverage:
        return 0

    if needing_update:
        print(f"  Proposals (first 10 of {len(needing_update)}):")
        for p in needing_update[:10]:
            current = repr(p.current_apply_module) if p.current_apply_module else "<unset>"
            print(f"    {p.patch_id:8s}  {current} → {p.proposed_apply_module!r}")
        if len(needing_update) > 10:
            print(f"    ... ({len(needing_update) - 10} more)")
        print()

    if args.emit_py:
        print(f"  Wrote Python snippet → {args.emit_py}")
    else:
        print("  Tip: re-run with `--emit-py mapping.py` to dump the")
        print("       mapping into a paste-friendly Python file.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
