#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""generate_configs_md.py — auto-generate model config inventory from builtin YAMLs.

Companion to scripts/generate_patches_md.py: this generates docs/CONFIGS_AUTO.md
from `vllm/sndr_core/model_configs/builtin/*.yaml` files. Operator-facing
config inventory с reference_metrics, lifecycle, target hardware.

Background: docs/CONFIGS.md was identified in 2026-05-11 audit as lacking
per-config TPS comparison table (Agent A). Manual updates lag behind YAML
changes. Auto-generation eliminates drift.

No torch/pyyaml dependency — uses simple regex parsing of top-level YAML
fields. Sufficient because builtin configs have canonical formatting.

Usage:
    python3 scripts/generate_configs_md.py             # writes docs/CONFIGS_AUTO.md
    python3 scripts/generate_configs_md.py --check     # CI gate, exit 1 on divergence
    python3 scripts/generate_configs_md.py --stdout    # print, no write
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUILTIN_DIR = REPO_ROOT / "vllm" / "sndr_core" / "model_configs" / "builtin"
OUTPUT_PATH = REPO_ROOT / "docs" / "CONFIGS_AUTO.md"


# Top-level fields to extract from each YAML
TOP_FIELDS = [
    "key", "title", "description", "lifecycle", "workload_tag",
    "last_validated", "genesis_pin", "vllm_pin_required",
    "model_path", "served_model_name", "kv_cache_dtype",
    "max_model_len", "gpu_memory_utilization", "max_num_seqs",
    "max_num_batched_tokens",
]

# Reference metrics fields
METRIC_FIELDS = [
    "long_gen_sustained_tps", "decode_tpot_ms", "ttft_ms",
    "tool_call_score", "stability_cv_pct",
]


def parse_yaml_top_level(yaml_path: Path) -> dict:
    """Parse top-level scalar fields from YAML.

    Limitations: doesn't handle nested structures or multi-line scalars
    (>- folded text). Sufficient for our flat top-level fields.
    """
    text = yaml_path.read_text()
    result: dict = {"_file": yaml_path.name}

    # Extract top-level scalar fields (key: value at indent 0)
    for field in TOP_FIELDS:
        # Match `field: value` at start of line, capture value до newline or comment
        # Handle quoted strings
        m = re.search(rf'^{field}:\s*(.+?)(?:\s+#.*)?$', text, flags=re.M)
        if m:
            val = m.group(1).strip()
            # Strip surrounding quotes
            if (val.startswith("'") and val.endswith("'")) or \
               (val.startswith('"') and val.endswith('"')):
                val = val[1:-1]
            # Skip multi-line markers
            if val in (">-", "|-", ">", "|"):
                # Try to capture first line of next block
                m2 = re.search(rf'^{field}:\s*>-?\s*\n((?:\s+\S.*\n)+)', text, flags=re.M)
                if m2:
                    val = m2.group(1).strip().replace("\n", " ").replace("  ", " ")
                else:
                    val = None
            result[field] = val
        else:
            result[field] = None

    # Extract reference_metrics block
    metrics_match = re.search(r'^reference_metrics:\s*\n((?:\s+.*\n)+?)(?=^\S|\Z)', text, flags=re.M)
    if metrics_match:
        metrics_block = metrics_match.group(1)
        for field in METRIC_FIELDS:
            m = re.search(rf'^\s+{field}:\s*(.+?)(?:\s+#.*)?$', metrics_block, flags=re.M)
            if m:
                val = m.group(1).strip()
                if (val.startswith("'") and val.endswith("'")) or \
                   (val.startswith('"') and val.endswith('"')):
                    val = val[1:-1]
                result[f"metric_{field}"] = val
            else:
                result[f"metric_{field}"] = None
    else:
        for field in METRIC_FIELDS:
            result[f"metric_{field}"] = None

    # Extract MTP K (spec_decode.num_speculative_tokens)
    mtp_match = re.search(r'spec_decode:\s*\n\s+method:\s*mtp\s*\n\s+num_speculative_tokens:\s*(\d+)', text, flags=re.M)
    if mtp_match:
        result["mtp_k"] = mtp_match.group(1)
    else:
        ngram_match = re.search(r'spec_decode:\s*\n\s+method:\s*ngram', text, flags=re.M)
        result["mtp_k"] = "ngram" if ngram_match else None

    # Count enabled patches in genesis_env
    enable_count = len(re.findall(r"^\s+GENESIS_ENABLE_\w+:\s*'1'", text, flags=re.M))
    result["enabled_patches"] = enable_count

    return result


def render_markdown(configs: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = []

    lines.append("# Genesis vLLM Patches — Model Config Inventory (auto-generated)")
    lines.append("")
    lines.append("> ⚠ **Auto-generated by `scripts/generate_configs_md.py` — DO NOT EDIT MANUALLY.**")
    lines.append("> Source: `vllm/sndr_core/model_configs/builtin/*.yaml`")
    lines.append("> Companion to curated [CONFIGS.md](CONFIGS.md) (narrative).")
    lines.append("")
    lines.append(f"Generated: {now}")
    lines.append(f"Total configs: **{len(configs)}**")
    lines.append("")

    # Statistics by lifecycle
    lifecycles: dict = {}
    for c in configs:
        lc = c.get("lifecycle") or "?"
        lifecycles[lc] = lifecycles.get(lc, 0) + 1

    lines.append("## By lifecycle")
    lines.append("")
    for lc, count in sorted(lifecycles.items()):
        lines.append(f"- `{lc}`: {count}")
    lines.append("")

    # Main config table
    lines.append("## Config matrix")
    lines.append("")
    lines.append("| Key | Lifecycle | Model | KV dtype | Spec | Max ctx | TPS | TPOT | Tool | Last validated |")
    lines.append("|---|:---:|---|---|:---:|---:|---:|---:|:---:|---|")

    # Sort: stable first, then tested, then experimental, then retired
    lifecycle_order = {"stable": 0, "tested": 1, "experimental": 2, "community-test": 3, "retired": 4}
    sorted_configs = sorted(configs, key=lambda c: (lifecycle_order.get(c.get("lifecycle") or "", 9), c.get("key") or ""))

    for c in sorted_configs:
        key = c.get("key") or c.get("_file", "").replace(".yaml", "")
        lifecycle = c.get("lifecycle") or "?"
        served = c.get("served_model_name") or "?"
        kv = c.get("kv_cache_dtype") or "default"
        mtp = c.get("mtp_k") or "—"
        mtp_str = f"MTP K={mtp}" if mtp not in (None, "ngram", "—") else (mtp or "—")
        max_ctx = c.get("max_model_len") or "?"
        tps = c.get("metric_long_gen_sustained_tps") or "—"
        tpot = c.get("metric_decode_tpot_ms") or "—"
        tool = c.get("metric_tool_call_score") or "—"
        validated = c.get("last_validated") or "—"
        lines.append(
            f"| `{key}` | `{lifecycle}` | {served} | `{kv}` | {mtp_str} | "
            f"{max_ctx} | {tps} | {tpot} | {tool} | {validated} |"
        )
    lines.append("")

    # Per-config details
    lines.append("## Per-config details")
    lines.append("")
    for c in sorted_configs:
        key = c.get("key") or c.get("_file", "")
        lines.append(f"### `{key}`")
        lines.append("")
        if c.get("title"):
            lines.append(f"**Title**: {c['title']}")
            lines.append("")
        if c.get("description"):
            desc = c["description"][:200].strip()
            lines.append(f"> {desc}")
            lines.append("")
        lines.append("**Engine config:**")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|---|---|")
        for field in ["lifecycle", "workload_tag", "genesis_pin", "vllm_pin_required",
                      "model_path", "kv_cache_dtype", "max_model_len",
                      "gpu_memory_utilization", "max_num_seqs", "max_num_batched_tokens"]:
            val = c.get(field) or "—"
            lines.append(f"| `{field}` | `{val}` |")
        lines.append(f"| `mtp_k` | {c.get('mtp_k') or '—'} |")
        lines.append(f"| `enabled_patches` (genesis_env) | {c.get('enabled_patches')} |")
        lines.append("")

        # Reference metrics if any
        if any(c.get(f"metric_{f}") for f in METRIC_FIELDS):
            lines.append("**Reference metrics (`genesis_bench_suite.py --quick`):**")
            lines.append("")
            lines.append("| Metric | Value |")
            lines.append("|---|---|")
            for f in METRIC_FIELDS:
                val = c.get(f"metric_{f}") or "—"
                lines.append(f"| `{f}` | `{val}` |")
            lines.append("")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Regenerate: `python3 scripts/generate_configs_md.py`")
    lines.append("Verify: `python3 scripts/generate_configs_md.py --check`")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not BUILTIN_DIR.is_dir():
        print(f"ERROR: builtin dir not found: {BUILTIN_DIR}", file=sys.stderr)
        return 2

    yaml_files = sorted(BUILTIN_DIR.glob("*.yaml"))
    if not yaml_files:
        print(f"ERROR: no YAML files in {BUILTIN_DIR}", file=sys.stderr)
        return 2

    configs = [parse_yaml_top_level(p) for p in yaml_files]
    content = render_markdown(configs)

    if args.stdout:
        print(content)
        return 0

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"FAIL: {OUTPUT_PATH.relative_to(REPO_ROOT)} doesn't exist", file=sys.stderr)
            return 1
        committed = OUTPUT_PATH.read_text()
        gen_norm = re.sub(r"Generated: \S+", "Generated: <TS>", content)
        com_norm = re.sub(r"Generated: \S+", "Generated: <TS>", committed)
        if gen_norm == com_norm:
            print(f"✓ {OUTPUT_PATH.relative_to(REPO_ROOT)} in sync ({len(configs)} configs)")
            return 0
        else:
            print(f"✗ {OUTPUT_PATH.relative_to(REPO_ROOT)} OUT OF SYNC", file=sys.stderr)
            return 1

    OUTPUT_PATH.write_text(content)
    print(f"✓ Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(configs)} configs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
